# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
prepare_react_native_project!
install! 'cocoapods', :disable_input_output_paths => true

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

def shared_pods
  
  pod 'Alamofire'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'AlamofireImage'
  pod 'GooglePlaces'
  pod 'GoogleMaps', '~> 3.9.0'
  pod 'Google-Maps-iOS-Utils'
  # pod 'NearbyMessages'
  pod 'FirebaseCrashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/DynamicLinks'
  pod 'SwiftyGif'
  pod 'SKCountryPicker'
  pod 'Mantis', '~> 1.3.2'
  pod 'Charts'
  pod 'PhoneNumberKit', '~> 2.6'
  pod 'Toast-Swift'
  # For Monthly AutoRenewalbe Subscription
  # pod 'SwiftyStoreKit'
  # Circular Progress In Nearby Interation Storyboard
  # pod "MBCircularProgressBar"
  # pod 'MBProgressHUD'
  pod 'DynamicBlurView'
  
end

target 'Blue' do
  # Comment the next line if you don't want to use dynamic frameworks
  config = use_native_modules!
  use_frameworks!
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  shared_pods
  # Pods for Blue
  
end

target 'BlueNotificationService' do
  use_frameworks!
  pod 'Alamofire'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'AlamofireImage'
end

target 'BlueNotificationExtension' do
  use_frameworks!
  pod 'Alamofire'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'AlamofireImage'
end

post_install do |installer|
  config = use_native_modules!
  react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  xcode_base_version = `xcodebuild -version | grep 'Xcode' | awk '{print $2}' | cut -d . -f 1`
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # For xcode 15+ only
      if config.base_configuration_reference && Integer(xcode_base_version) >= 15
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
    end
  end
end